name: Jenny Kao
description: just another blog
meta_description: "blogging about stuffs"
remote_theme: rosario/kasper
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/jennykao"
domain_name: "http://jennymhkao.github.io"
google_analytics: "UA-XXXXXXXX-X"

# Details for the RSS feed generator
url: ""
author: "Jenny Kao"P

# Disqus config
disqus-shortname: ""

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jekyll-paginate